name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔐 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace
          config: |
            Host *
              StrictHostKeyChecking no

      - name: 🏷️ Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DOCKER_COMPOSE_FILE=docker-compose.yaml" >> $GITHUB_ENV
            echo "APP_ENV=${{ secrets.APP_ENV_PRODUCTION }}" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/opt/portfolio" >> $GITHUB_ENV
            echo "PORT=3000" >> $GITHUB_ENV
          else
            echo "DOCKER_COMPOSE_FILE=docker-compose.staging.yaml" >> $GITHUB_ENV
            echo "APP_ENV=${{ secrets.APP_ENV_STAGING }}" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/opt/portfolio" >> $GITHUB_ENV
            echo "PORT=3001" >> $GITHUB_ENV
          fi

      - name: 🚀 Deploy to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          APP_ENV: ${{ env.APP_ENV }}
          DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}
          DEPLOY_PATH: ${{ env.DEPLOY_PATH }}
        run: |
          # Vérifier la connexion SSH
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo SSH connection successful"
          
          # Déployer l'application
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "\
            cd $DEPLOY_PATH && \
            docker compose -f $DOCKER_COMPOSE_FILE pull && \
            docker compose -f $DOCKER_COMPOSE_FILE up -d && \
            docker system prune -f"

      - name: 🏥 Health Check
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PORT: ${{ env.PORT }}
        run: |
          echo "Waiting for application to be ready..."
          sleep 15
          
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if curl -sSf "http://$SSH_HOST:$PORT" > /dev/null 2>&1; then
              echo "✅ Application is running successfully on port $PORT"
              exit 0
            else
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "Retry $RETRY_COUNT/$MAX_RETRIES - Waiting 10 seconds..."
                sleep 10
              fi
            fi
          done
          
          echo "❌ Application failed to start after $MAX_RETRIES attempts"
          exit 1