name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🐳 Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: 🐳 Install Docker Compose
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version

      - name: 🏷️ Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DOCKER_COMPOSE_FILE=docker-compose.yaml" >> $GITHUB_ENV
            echo "APP_ENV=${{ secrets.APP_ENV_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "DOCKER_COMPOSE_FILE=docker-compose.staging.yaml" >> $GITHUB_ENV
            echo "APP_ENV=${{ secrets.APP_ENV_STAGING }}" >> $GITHUB_ENV
          fi

      - name: 🐳 Deploy with Docker Compose
        env:
          APP_ENV: ${{ env.APP_ENV }}
          DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}
        run: |
          docker compose -f ${DOCKER_COMPOSE_FILE} pull
          docker compose -f ${DOCKER_COMPOSE_FILE} up -d